using Microsoft.EntityFrameworkCore;
using ResQ.API.Device_Management.Domain.Model.Aggregates;
using ResQ.API.Device_Management.Domain.Model.Entities;
using ResQ.API.Device_Management.Domain.Model.ValueObjects;

namespace ResQ.API.Device_Management.Infrastructure.Persistence.EFC.Configuration.Extensions;

/// <summary>
/// Extension methods for configuring the Device Management persistence model.
/// </summary>
public static class ModelBuilderExtensions
{
    /// <summary>
    /// Applies the Device Management entity configurations.
    /// </summary>
    /// <param name="builder">The model builder.</param>
    public static ModelBuilder ApplyDeviceManagementConfiguration(this ModelBuilder builder)
    {
        builder.Entity<Device>().ToTable("Devices");
        builder.Entity<Device>().HasKey(d => d.Id);
        
        // Device Id is generated by the aggregate
        builder.Entity<Device>().Property(d => d.Id).ValueGeneratedNever();
        builder.Entity<Device>().Property(d => d.OrganizationId).IsRequired();

        // DeviceCode Value Object
        builder.Entity<Device>().Property(d => d.DeviceCode).HasConversion(deviceCode => deviceCode.Value, value => DeviceCode.Create(value))
            .HasColumnName("DeviceCode").HasMaxLength(64).IsRequired();
        builder.Entity<Device>().Property(d => d.Name).HasMaxLength(120).IsRequired();
        builder.Entity<Device>().Property(d => d.Description).HasMaxLength(500);
        builder.Entity<Device>().Property(d => d.AdministrativeStatus).HasConversion<string>().HasMaxLength(20).IsRequired();
        builder.Entity<Device>().Property(d => d.CreatedAt).IsRequired();
        builder.Entity<Device>().Property(d => d.UpdatedAt).IsRequired();
        builder.Entity<Device>().Property(d => d.Version).IsRequired();

        // DeviceCode must be unique inside an organization
        builder.Entity<Device>()
            .HasIndex(d => new
            {
                d.OrganizationId,
                d.DeviceCode
            })
            .IsUnique();

        // Embedded Pattern for DeviceSpecifications
        builder.Entity<Device>().OwnsOne(d => d.Specifications, specifications =>
        {
            specifications.Property(s => s.Manufacturer).HasColumnName("Manufacturer").HasMaxLength(100);
            specifications.Property(s => s.Model).HasColumnName("Model").HasMaxLength(100);
            specifications.Property(s => s.SerialNumber).HasColumnName("SerialNumber").HasMaxLength(100);
        });

        // Embedded Pattern for DeviceAssignment
        builder.Entity<Device>().OwnsOne(d => d.Assignment, assignment =>
        {
            assignment.Property(a => a.BuildingId).HasColumnName("BuildingId").IsRequired();
            assignment.Property(a => a.ZoneId).HasColumnName("ZoneId");
        });

        // Embedded Pattern for ExternalDeviceReference
        builder.Entity<Device>().OwnsOne(d => d.ExternalReference, reference =>
        {
            reference.Property(r => r.SourceSystem).HasColumnName("ExternalSourceSystem").HasMaxLength(80);
            reference.Property(r => r.ExternalDeviceId).HasColumnName("ExternalDeviceId").HasMaxLength(120);
        });

        // DeviceCapability belongs to the Device Aggregate
        builder.Entity<DeviceCapability>().ToTable("DeviceCapabilities");
        builder.Entity<DeviceCapability>().HasKey(c => c.Id);
        builder.Entity<DeviceCapability>().Property(c => c.Id).ValueGeneratedNever();
        builder.Entity<DeviceCapability>().Property(c => c.Code).HasMaxLength(80).IsRequired();
        builder.Entity<DeviceCapability>().Property(c => c.Kind).HasConversion<string>().HasMaxLength(20).IsRequired();
        builder.Entity<DeviceCapability>().Property(c => c.Unit).HasMaxLength(30);
        builder.Entity<Device>().HasMany(d => d.Capabilities).WithOne().HasForeignKey("DeviceId").OnDelete(DeleteBehavior.Cascade);

        return builder;
    }
}